Repository lunarway/shuttle, pull requests merged in 2023-05, with the labels that each got.

#161 fix(deps): update external go packages
  go.mod
  go.sum
Labels: dependencies

#163 fix: only exclude
  pkg/executors/golang/discover/discover.go
Labels: patch

#162 feat: use return types when calling the cmder functions
  pkg/executors/golang/cmder/cmder.go
  pkg/executors/golang/cmder/cmder_test.go
Labels: minor
