Repository lunarway/shuttle, pull requests merged in 2023-12, with the labels that each got.

#198 chore(deps): update actions/setup-go action to v4
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: dependencies

#194 fix/send normal output to stderr
  cmd/config_test.go
  cmd/plan_test.go
  cmd/run_test.go
  pkg/executors/shell.go
  pkg/git/git.go
  pkg/ui/ui.go
Labels: patch

#202 chore(deps): update goreleaser/goreleaser-action action to v5
  .github/workflows/release.yml
Labels: dependencies

#201 chore(deps): update actions/setup-go action to v5
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: dependencies

#199 feat: add support for workspaces and external modules in the same repo
  pkg/executors/golang/codegen/mod_file.go
  pkg/executors/golang/codegen/mod_file_test.go
  pkg/executors/golang/codegen/module.go
  pkg/executors/golang/codegen/patch.go
  pkg/executors/golang/codegen/patch_default.go
  pkg/executors/golang/codegen/patch_finder.go
  pkg/executors/golang/codegen/patch_gomodule.go
  pkg/executors/golang/codegen/patch_patcher.go
  pkg/executors/golang/codegen/patch_test.go
  pkg/executors/golang/codegen/patch_workspace.go
  pkg/executors/golang/codegen/testdata/patch/replace_existing/.shuttle/actions/tmp/go.mod
  pkg/executors/golang/codegen/testdata/patch/replace_existing/go.mod
  pkg/executors/golang/codegen/testdata/patch/root_module/.shuttle/actions/tmp/go.mod
  pkg/executors/golang/codegen/testdata/patch/root_module/go.mod
  pkg/executors/golang/codegen/testdata/patch/root_workspace/.shuttle/actions/tmp/go.mod
  pkg/executors/golang/codegen/testdata/patch/root_workspace/go.mod
  pkg/executors/golang/codegen/testdata/patch/root_workspace/go.work
  pkg/executors/golang/codegen/testdata/patch/root_workspace/other/subpackage/go.mod
  pkg/executors/golang/codegen/testdata/patch/root_workspace/subpackage/go.mod
  pkg/executors/golang/compile/compile.go
  pkg/executors/golang/compile/matcher/matcher.go
  pkg/executors/golang/executer/prepare.go
  pkg/executors/golang/executer/run.go
  pkg/executors/task.go
Labels: minor

#203 feat/with golang action args
  cmd/cmd.go
  pkg/executors/golang/cmder/cmder.go
  pkg/executors/golang/compile/compile.go
  pkg/executors/golang/executer/actions.go
  pkg/executors/golang/executer/actions_test.go
  pkg/executors/golang/executer/executer.go
  pkg/executors/golang/executer/list.go
Labels: minor

#204 feat: with shuttle available outside of a repository
  cmd/cmd.go
  cmd/run.go
  cmd/run_test.go
Labels: minor

#207 feat: disable fallback by default, return nothing if no builder is found
  docs/features/golang-actions.md
  pkg/executors/golang/compile/compile.go
  pkg/executors/golang/errors/errors.go
  pkg/executors/golang/executer/list.go
  pkg/executors/golang/executer/prepare.go
  pkg/executors/golang/executer/run.go
Labels: minor
