Repository lunarway/shuttle, pull requests merged in 2023-07, with the labels that each got.

#166 fix(deps): update external go packages
  go.mod
  go.sum
Labels: dependencies

#165 feat/with telemetry
  cmd/cmd.go
  cmd/run.go
  cmd/telemetry.go
  cmd/template.go
  go.mod
  go.sum
  pkg/executors/golang/executer/executer.go
  pkg/executors/shell.go
  pkg/telemetry/context.go
  pkg/telemetry/jsonlines.go
  pkg/telemetry/logging.go
  pkg/telemetry/noop.go
  pkg/telemetry/setup.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/utility.go
Labels: minor

#168 chore: fmt
  cmd/config.go
  cmd/config_test.go
  cmd/get.go
  cmd/get_test.go
  cmd/has.go
  cmd/ls.go
  cmd/ls_test.go
  cmd/plan.go
  cmd/run_test.go
  cmd/template_test.go
  cmd/test.go
  cmd/version.go
  pkg/config/planargument.go
  pkg/config/shuttleconfig.go
  pkg/config/shuttleconfig_test.go
  pkg/config/shuttleplan.go
  pkg/config/shuttleplan_test.go
  pkg/executors/docker.go
  pkg/executors/executor.go
  pkg/executors/golang/codegen/codegen.go
  pkg/executors/golang/compile/compile_test.go
  pkg/executors/golang/discover/discover_test.go
  pkg/executors/golang/executer/list.go
  pkg/executors/golang/executer/prepare.go
  pkg/executors/golang/executer/run.go
  pkg/executors/golang/executer/run_test.go
  pkg/executors/golang/parser/parser.go
  pkg/executors/golang/shuttlefolder/prepare.go
  pkg/executors/help.go
  pkg/executors/help_test.go
  pkg/executors/task.go
  pkg/git/status.go
  pkg/sdk/context.go
  pkg/sdk/template.go
  pkg/sdk/template_test.go
  pkg/telemetry/jsonlines.go
  pkg/templates/funcs_test.go
Labels: patch

#170 feat/with partitioned json files
  cmd/run.go
  cmd/telemetry.go
  cmd/template.go
  pkg/telemetry/context.go
  pkg/telemetry/context_test.go
  pkg/telemetry/jsonlines.go
  pkg/telemetry/uploader.go
  pkg/telemetry/uploader_test.go
  pkg/telemetry/utility.go
Labels: minor

#174 docs: document telemetry
  docs/features/telemetry.md
  pkg/telemetry/uploader.go
Labels: patch

#176 feat/with arg hashing
  pkg/telemetry/uploader.go
  pkg/telemetry/utility.go
Labels: patch

#179 docs: add docs to featuers
  README.md
  docs/features/golang-actions.md
Labels: patch

#180 feat: fix goreleaser
  .goreleaser.yml
Labels: minor
