Repository lunarway/shuttle, pull requests merged in 2024-08, with the labels that each got.

#240 chore(deps): update golang docker tag to v1.22.6
  .github/workflows/build.yml
  .github/workflows/release.yml
  pkg/executors/golang/compile/compile.go
Labels: dependencies

#241 chore(deps): update golang docker tag to v1.23.0
  .github/workflows/build.yml
  .github/workflows/release.yml
  pkg/executors/golang/compile/compile.go
Labels: dependencies

#242 feat/silence usage for shuttle actions
  cmd/run.go
  cmd/run_test.go
  pkg/executors/golang/cmder/cmder.go
Labels: minor

#243 fix: goreleaser, which were on version 1 before
  .github/workflows/release.yml
  .goreleaser.yml
Labels: patch
