Repository lunarway/shuttle, pull requests merged in 2024-01, with the labels that each got.

#209 fix shuttle should search recursively for shuttle files
  cmd/cmd.go
  cmd/cmd_test.go
Labels: patch

#211 chore(deps): update golang docker tag to v1.21.6
  pkg/executors/golang/compile/compile.go
Labels: dependencies

#213 fix: double hash in value
  cmd/run.go
  cmd/run_test.go
Labels: patch

#216 feat: use awk instead of grep
  action.yml
Labels: minor

#217 chore(deps): update actions/cache action to v4
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: dependencies

#218 feat: disable actions by default
  pkg/executors/golang/executer/list.go
  pkg/executors/golang/executer/list_test.go
  pkg/executors/golang/executer/run_test.go
Labels: minor
